import * as fs from "node:fs/promises";
import * as path from "node:path";
import sharp from "sharp";

/**
 * 各ストーリーの背景画像を Wikimedia Commons から取得して
 * output/YYYY-MM-DD/_assets/ に保存する。build-news-video.ts の前に必ず実行する。
 *
 * 出力 (各 story / code 例: lb, co, rw):
 *   _assets/bg-{code}-1..6.jpg   (1080x1920, ニュース関連, CC/PD)
 *   _assets/{code}.png           (国旗, flagcdn 由来 = Wikimedia-derived PD)
 *   _assets/CREDITS.md           (出典・ライセンス一覧)
 *
 * 入力:  output/YYYY-MM-DD/script-en.json
 *
 * 設計方針:
 *   - 国名 + 見出しの固有名詞/トピック語で Commons を検索し、記事に関連する写真を選ぶ
 *   - bg-1..6 は「必ず」存在させる (取得数が足りなければ cycle、ゼロなら単色フォールバック)
 *   - 国営プロパガンダ系ソースは Commons 検索では問題にならないが、flag/logo/地図アイコンは除外
 */

const W = 1080;
const H = 1920;
const BG_COUNT = 6;

interface Story {
  index: number;
  country: { code: string; flag: string; name?: string };
  headline: string;
  summary: string;
  sourceName: string;
  sourceUrl: string;
}
interface ScriptJson { date: string; stories: Story[] }

interface CommonsImage {
  title: string;
  thumbUrl: string;
  descUrl: string;
  license: string;
  artist: string;
}

// ISO 3166-1 alpha-2 → 英語国名 (世界ニュースで頻出する国を網羅)。未知コードは code をそのまま使う。
const COUNTRY_NAMES: Record<string, string> = {
  US: "United States", GB: "United Kingdom", FR: "France", DE: "Germany", IT: "Italy",
  ES: "Spain", PT: "Portugal", NL: "Netherlands", BE: "Belgium", CH: "Switzerland",
  AT: "Austria", SE: "Sweden", NO: "Norway", DK: "Denmark", FI: "Finland", IE: "Ireland",
  PL: "Poland", UA: "Ukraine", RU: "Russia", BY: "Belarus", CZ: "Czech Republic",
  GR: "Greece", TR: "Turkey", RO: "Romania", HU: "Hungary",
  CN: "China", JP: "Japan", KR: "South Korea", KP: "North Korea", IN: "India",
  PK: "Pakistan", BD: "Bangladesh", ID: "Indonesia", MY: "Malaysia", SG: "Singapore",
  TH: "Thailand", VN: "Vietnam", PH: "Philippines", TW: "Taiwan",
  IL: "Israel", LB: "Lebanon", SY: "Syria", IQ: "Iraq", IR: "Iran", SA: "Saudi Arabia",
  AE: "United Arab Emirates", QA: "Qatar", KW: "Kuwait", YE: "Yemen", JO: "Jordan",
  EG: "Egypt", LY: "Libya", TN: "Tunisia", DZ: "Algeria", MA: "Morocco", SD: "Sudan",
  ET: "Ethiopia", KE: "Kenya", NG: "Nigeria", GH: "Ghana", ZA: "South Africa",
  CD: "Democratic Republic of the Congo", RW: "Rwanda", UG: "Uganda", TZ: "Tanzania",
  SO: "Somalia", ML: "Mali", SN: "Senegal", CM: "Cameroon",
  CA: "Canada", MX: "Mexico", BR: "Brazil", AR: "Argentina", CL: "Chile",
  CO: "Colombia", PE: "Peru", VE: "Venezuela", EC: "Ecuador", BO: "Bolivia",
  AU: "Australia", NZ: "New Zealand",
};

// 見出しに含まれていたら背景クエリのトピック語として優先するテーマ。
const TOPIC_TERMS = [
  "election", "vote", "president", "parliament", "protest", "war", "conflict",
  "military", "army", "missile", "nuclear", "energy", "earthquake", "flood",
  "storm", "wildfire", "drought", "summit", "treaty", "deal", "economy",
  "inflation", "court", "trial", "border", "refugee", "health", "outbreak",
  "virus", "vaccine", "climate", "oil", "gas", "trade", "ceasefire", "peace",
];

const STOPWORDS = new Set([
  "the", "a", "an", "as", "of", "in", "on", "to", "for", "and", "or", "with",
  "into", "over", "after", "before", "amid", "says", "say", "new", "deal",
  "today", "year", "years", "day", "days", "week", "month",
]);

const COMMONS_API = "https://commons.wikimedia.org/w/api.php";
const USER_AGENT = "DailyWorld60/1.0 (news shorts pipeline; contact info@hero-english.net)";

async function main() {
  const date = process.argv[2] ?? new Date().toISOString().slice(0, 10);
  const dir = path.join("output", date);
  const assets = path.join(dir, "_assets");
  await fs.mkdir(assets, { recursive: true });

  const script: ScriptJson = JSON.parse(await fs.readFile(path.join(dir, "script-en.json"), "utf-8"));

  const creditLines: string[] = [
    "# Image Credits (auto-fetched, Wikimedia Commons)",
    "",
    `Generated by scripts/fetch-broll.ts for ${date}.`,
    "Background images sourced from Wikimedia Commons (CC-BY / CC-BY-SA / PD).",
    "Flag PNGs from flagcdn.com (Wikimedia-derived, PD).",
    "",
  ];

  for (const story of script.stories) {
    const code = story.country.code.toLowerCase();
    const countryName = story.country.name ?? COUNTRY_NAMES[story.country.code.toUpperCase()] ?? story.country.code;

    const queries = buildQueries(countryName, story.headline);
    console.log(`[broll] ${code} (${countryName}) queries: ${queries.join(" | ")}`);

    const picked: CommonsImage[] = [];
    const seen = new Set<string>();
    for (const q of queries) {
      if (picked.length >= BG_COUNT) break;
      const imgs = await searchCommons(q).catch(e => {
        console.warn(`[broll] search failed for "${q}": ${e instanceof Error ? e.message : e}`);
        return [] as CommonsImage[];
      });
      for (const img of imgs) {
        if (picked.length >= BG_COUNT) break;
        if (seen.has(img.title)) continue;
        seen.add(img.title);
        picked.push(img);
      }
    }

    creditLines.push(`## Story ${story.index} — ${countryName}: ${story.headline}`);

    // 取得画像を 1080x1920 にクロップして bg-{code}-N.jpg へ。
    const savedBg: number[] = [];
    for (let i = 0; i < picked.length && i < BG_COUNT; i++) {
      const img = picked[i];
      const dest = path.join(assets, `bg-${code}-${i + 1}.jpg`);
      try {
        await downloadAndCrop(img.thumbUrl, dest);
        savedBg.push(i + 1);
        creditLines.push(`- bg-${code}-${i + 1}.jpg — ${img.title} (${img.license || "see Commons"}) ${img.artist ? `by ${stripHtml(img.artist)}` : ""}\n  ${img.descUrl}`);
      } catch (e) {
        console.warn(`[broll] download/crop failed (${img.title}): ${e instanceof Error ? e.message : e}`);
      }
    }

    // 1 枚も取れなかった場合: 国名のみで広く再検索 → それでもダメなら単色フォールバック。
    if (savedBg.length === 0) {
      const fallbackImgs = await searchCommons(countryName).catch(() => [] as CommonsImage[]);
      for (let i = 0; i < fallbackImgs.length && savedBg.length < BG_COUNT; i++) {
        const dest = path.join(assets, `bg-${code}-${savedBg.length + 1}.jpg`);
        try {
          await downloadAndCrop(fallbackImgs[i].thumbUrl, dest);
          savedBg.push(savedBg.length + 1);
          creditLines.push(`- bg-${code}-${savedBg.length}.jpg — ${fallbackImgs[i].title} (fallback)\n  ${fallbackImgs[i].descUrl}`);
        } catch { /* keep trying */ }
      }
    }
    if (savedBg.length === 0) {
      await solidFallback(path.join(assets, `bg-${code}-1.jpg`), countryName);
      savedBg.push(1);
      creditLines.push(`- bg-${code}-1.jpg — solid-color fallback (no Commons image found)`);
      console.warn(`[broll] ${code}: no Commons image, used solid fallback`);
    }

    // bg-1..6 を必ず揃える: 不足分は取得済みを cycle してコピー。
    for (let n = 1; n <= BG_COUNT; n++) {
      const target = path.join(assets, `bg-${code}-${n}.jpg`);
      if (await exists(target)) continue;
      const src = path.join(assets, `bg-${code}-${savedBg[(n - 1) % savedBg.length]}.jpg`);
      await fs.copyFile(src, target).catch(() => {});
    }

    // 国旗 PNG
    await fetchFlag(story.country.code, path.join(assets, `${code}.png`)).catch(e => {
      console.warn(`[broll] flag fetch failed (${code}): ${e instanceof Error ? e.message : e}`);
    });

    creditLines.push("");
    console.log(`[broll] ${code}: ${savedBg.length} unique bg saved, bg-1..6 ensured`);
  }

  await fs.writeFile(path.join(assets, "CREDITS.md"), creditLines.join("\n"), "utf-8");
  console.log(`[broll] done → ${assets}`);
}

/** 見出し + 国名から Commons 検索クエリを構築する (記事関連の写真を狙う)。 */
function buildQueries(countryName: string, headline: string): string[] {
  const words = headline.replace(/[^\w\s]/g, " ").split(/\s+/).filter(Boolean);
  const lower = words.map(w => w.toLowerCase());

  // 固有名詞 (国名以外の大文字始まり、先頭語は除外して誤検出を避ける)
  const proper = words
    .slice(1)
    .filter(w => /^[A-Z][a-zA-Z]{2,}/.test(w) && w.toLowerCase() !== countryName.toLowerCase());
  // トピック語
  const topics = lower.filter(w => TOPIC_TERMS.includes(w));
  // その他の意味語
  const content = lower.filter(w => w.length > 3 && !STOPWORDS.has(w) && !TOPIC_TERMS.includes(w));

  const q: string[] = [];
  if (proper.length) q.push(`${countryName} ${proper.slice(0, 2).join(" ")}`);
  if (topics.length) q.push(`${countryName} ${topics[0]}`);
  if (content.length) q.push(`${countryName} ${content[0]}`);
  q.push(countryName);
  // 重複除去
  return [...new Set(q.map(s => s.trim()).filter(Boolean))];
}

/** Wikimedia Commons 画像検索。記事背景に向く大きめの写真のみ返す。 */
async function searchCommons(query: string): Promise<CommonsImage[]> {
  const params = new URLSearchParams({
    action: "query",
    format: "json",
    generator: "search",
    gsrsearch: `${query} filetype:bitmap`,
    gsrnamespace: "6",
    gsrlimit: "12",
    prop: "imageinfo",
    iiprop: "url|extmetadata|mime|size",
    iiurlwidth: "1280",
  });
  const res = await fetch(`${COMMONS_API}?${params}`, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) throw new Error(`Commons HTTP ${res.status}`);
  const json = await res.json() as {
    query?: { pages?: Record<string, {
      title: string;
      imageinfo?: Array<{
        thumburl?: string; url?: string; descriptionurl?: string;
        mime?: string; width?: number; height?: number;
        extmetadata?: Record<string, { value?: string }>;
      }>;
    }> };
  };
  const pages = json.query?.pages ? Object.values(json.query.pages) : [];
  const out: Array<CommonsImage & { area: number; isJpeg: boolean }> = [];
  for (const p of pages) {
    const ii = p.imageinfo?.[0];
    if (!ii) continue;
    if (!ii.mime || !/image\/(jpeg|png)/.test(ii.mime)) continue;
    if ((ii.width ?? 0) < 800) continue;
    const title = p.title.replace(/^File:/, "");
    // 背景に不向きな素材を除外: 国旗/ロゴ/地図/紋章アイコン類 + チャート/図表/文書スキャン類
    if (/\b(flag|logo|icon|coat of arms|seal|emblem|locator)\b/i.test(title)) continue;
    if (/\b(map|chart|diagram|graph|infographic|statistics|expectancy|decree|document|results table)\b/i.test(title)) continue;
    if (/указ|диаграмм|карта/i.test(title)) continue; // ロシア語: 法令/図表/地図
    const md = ii.extmetadata ?? {};
    out.push({
      title,
      thumbUrl: ii.thumburl ?? ii.url ?? "",
      descUrl: ii.descriptionurl ?? `https://commons.wikimedia.org/wiki/${encodeURIComponent(p.title)}`,
      license: md.LicenseShortName?.value ?? "",
      artist: md.Artist?.value ?? "",
      area: (ii.width ?? 0) * (ii.height ?? 0),
      isJpeg: /jpeg/.test(ii.mime),
    });
  }
  // 写真(jpeg)を優先し、その中で解像度の高い順。検索 relevance はおおむね保たれる。
  out.sort((a, b) => (Number(b.isJpeg) - Number(a.isJpeg)) || (b.area - a.area));
  return out.filter(i => i.thumbUrl).map(({ area, isJpeg, ...rest }) => { void area; void isJpeg; return rest; });
}

/** 画像をダウンロードして 1080x1920 cover crop で保存。 */
async function downloadAndCrop(url: string, dest: string): Promise<void> {
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) throw new Error(`download HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await sharp(buf)
    .resize(W, H, { fit: "cover", position: "attention" })
    .jpeg({ quality: 86 })
    .toFile(dest);
}

/** Commons から何も取れなかった時の単色フォールバック (黒画面回避)。 */
async function solidFallback(dest: string, label: string): Promise<void> {
  const svg = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
       <rect width="${W}" height="${H}" fill="#0F1B3D"/>
     </svg>`,
  );
  await sharp(svg).jpeg({ quality: 86 }).toFile(dest);
  void label;
}

/** 国旗 PNG を flagcdn から取得 (640x480, hook の {code}.png と同寸)。 */
async function fetchFlag(code: string, dest: string): Promise<void> {
  const iso = code.toLowerCase();
  const res = await fetch(`https://flagcdn.com/w640/${iso}.png`, { headers: { "User-Agent": USER_AGENT } });
  if (!res.ok) throw new Error(`flag HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await fs.writeFile(dest, buf);
}

function stripHtml(s: string): string {
  return s.replace(/<[^>]+>/g, "").trim().slice(0, 80);
}
async function exists(p: string): Promise<boolean> {
  return fs.access(p).then(() => true).catch(() => false);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
